server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false

# maxmind geo service
geo.db.file.path: classpath:GeoLite2-City.mmdb

# database properties
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 10
    flyway:
      table: schema_version
      schemas: columbus
info:
  version: @project.version@
  stage: dev
  damsel.version: @damsel.version@